name: Update Directory Options

on:
  workflow_dispatch:
  
jobs:
  update_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: List directories
        id: list_dirs
        run: |
          chmod +x ./scripts/list_dirs.sh
          ./scripts/list_dirs.sh > directories.txt

      - name: Update workflow file
        run: |
          # Read the directories
          dirs=$(cat directories.txt)
          # Generate options list
          options=$(echo "$dirs" | sed "s/^/- '/")
          # Update the workflow YAML file with new options
          sed -i "/options:/,/^$/d" .github/workflows/main.yml
          sed -i "/workflow_dispatch:/a \ \ \ \ options:\n$options" .github/workflows/main.yml

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .github/workflows/main.yml
          git commit -m "Update workflow with new directories"
          git push
