config-version: 1


snowflake-account: 'xy12345.east-us-2.azure'
snowflake-warehouse: 'warehouse'
snowflake-database: 'SOWMYA_DB'
snowflake-schema: null
snowflake-user: 'sowmya018'
snowflake-role: 'role'
change-history-table: 'SOWMYA_DB.SCHEMACHANGE.CHANGE_HISTORY'
create-change-history-table: true

# Define values for the variables to replaced in change scripts
vars:
  schemas:
    schema_1: 'SOWMYA_DB.schema1'
