name: Manual Dispatch Example

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'World'
        type: choice
        options:
          - World
          - Alice
          - Bob
      greeting:
        description: 'Greeting message'
        required: true
        default: 'Hello'
        type: choice
        options:
          - Hello
          - Hi
          - Hey

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print greeting
        run: echo "${{ github.event.inputs.greeting }} ${{ github.event.inputs.name }}!"
