config-version: 1

snowflake-account: 'ne99457.ap-southeast-1'
snowflake-warehouse: 'COMPUTE_WH'
snowflake-database: 'SOWMYA_DB'
snowflake-schema: null
snowflake-role: 'ACCOUNTADMIN'
change-history-table: 'SOWMYA_DB.SCHEMACHANGE.CHANGE_HISTORY'
create-change-history-table: true

# Define values for the variables to replaced in change scripts
vars:
  schemas:
    schema_1: 'SOWMYA_DB.schema1'
    schema_2: 'SOWMYA_DB.schema2'
    schema_3: 'SOWMYA_DB.schema3'
    schema_4: 'SOWMYA_DB.schema3'
