config-version: 1


snowflake_account: 'ne99457.ap-southeast-1'
snowflake_warehouse: 'COMPUTE_WH'
snowflake_database: 'SOWMYA_DB'
snowflake_schema: null
snowflake_role: 'ACCOUNTADMIN'
change-history-table: 'SOWMYA_DB.SCHEMACHANGE.CHANGE_HISTORY'
create-change-history-table: true

# Define values for the variables to replaced in change scripts
vars:
  schemas:
    schema_1: 'SOWMYA_DB.schema1'
