name: Build and Push Docker Image to JFrog Artifactory

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to JFrog Artifactory Docker registry
        run: |
           docker login ${{ secrets.JFROG_REGISTRY }} -u ${{ secrets.JFROG_USERNAME }} --password ${{ secrets.JFROG_IDENTITY_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.JFROG_REGISTRY }}schemachange:1.1.0 .

      - name: Push Docker image to JFrog Artifactory
        run: |
          docker push ${{ secrets.JFROG_REGISTRY }}schemachange:1.1.0
