name: Build and Push Docker Image to JFrog

on:
  push:
    branches:
      - main
  workflow_dispatch:   # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get JFrog Identity Token
        id: get_token
        env:
          JFROG_BASE_URL: ${{ secrets.JFROG_BASE_URL }}
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_IDENTITY_TOKEN: ${{ secrets.JFROG_IDENTITY_TOKEN }}
        run: |
          echo JFROG_BASE_URL
          echo JFROG_USERNAME
          echo "::set-output name=token::${JFROG_IDENTITY_TOKEN}"

      - name: Log in to JFrog Artifactory
        run: |
          echo ${{ steps.get_token.outputs.token }} | docker login ${{ secrets.JFROG_REGISTRY }} -u ${{ secrets.JFROG_USERNAME }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.JFROG_REGISTRY }}schemachange-docker/schemachange:1.1.0
