name: Pull Docker Image and Run schemachange Dry Run

on:
  workflow_dispatch:   # Allow manual triggering

jobs:
  run_schemachange:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Encode credentials to base64
        id: encode
        run: |
          echo -n "${{ secrets.SNOWFLAKE_PASSWORD }}" | base64 > snowflake_password_base64.txt
          echo -n "${{ secrets.JFROG_IDENTITY_TOKEN }}" | base64 > jfrog_identity_token_base64.txt

      - name: Log in to JFrog Artifactory
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
        run: |
          base64 --decode jfrog_identity_token_base64.txt | docker login ${{ secrets.JFROG_REGISTRY }} -u ${{ secrets.JFROG_USERNAME }} --password-stdin

      - name: Pull Docker image
        run: docker pull ${{ secrets.JFROG_REGISTRY }}/schemachange:latest
 
      - name: Run schemachange dry run
        id: schemachange
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: $(snowflake_password_base64.txt)
        run: |
          docker run --rm -v ${{ github.workspace }}/instances/schemachange:/instances/schemachange \
          -e SNOWFLAKE_PASSWORD=$SNOWFLAKE_PASSWORD \
          ${{ secrets.JFROG_REGISTRY }}/schemachange:latest \
          deploy \
          -f /instances/schemachange/scripts/versioned/sowmya_db \
          --config-folder /instances/schemachange/config/nonprod-us-east-2/sowmya_db/prod \
          -u $SNOWFLAKE_USER --dry-run

      - name: Clean up Docker config
        run: |
          rm -f ~/.docker/config.json
