name: Build schemachange Docker Image
run-name: Build schemachange Docker Image in JFrog

on:
  workflow_dispatch:   # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.JFROG_REGISTRY }}
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_IDENTITY_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./instances/schemachange
          file: ./instances/schemachange/DockerFile
          push: true
          tags:  ${{ secrets.JFROG_REGISTRY }}/schemachange:latest
