name: Setup Directories

on:
  workflow_dispatch:
    inputs:
      dir_type:
        description: 'Select type of scripts'
        required: true
        type: choice
        options:
          - 'versioned'
          - 'always'
          - 'repeatable'

jobs:
  list_folders:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.list_folders.outputs.options }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List folders
        id: list_folders
        uses: ./.github/actions/schemachange
        with:
          dir_type: ${{ github.event.inputs.dir_type }}

      - name: Set directories output
        id: set_directories
        run: |
          directories=$(cat directories.txt | tr '\n' ',')
          echo "::set-output name=directories::$directories"
